# Generated by Django 2.0.4 on 2018-04-07 15:41
TIME_ZONE = 'Asia/Wuhan'#'UTC'

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_title', models.CharField(max_length=128)),
                ('ask_time', models.DateTimeField()),
                ('ask_details', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_details', models.CharField(max_length=3000)),
                ('com_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LabelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lb_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_details', models.TextField()),
                ('re_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=16)),
                ('sex', models.CharField(choices=[('f', '男'), ('m', '女')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='askinfo',
            name='ask_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iknow.UserInfo'),
        ),
    ]
