# Generated by Django 2.0.4 on 2018-04-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0002_auto_20180408_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelinfo',
            name='lb_ask',
            field=models.ManyToManyField(to='Iknow.AskInfo'),
        ),
        migrations.AddField(
            model_name='labelinfo',
            name='lb_user',
            field=models.ManyToManyField(to='Iknow.UserInfo'),
        ),
        migrations.AlterField(
            model_name='askinfo',
            name='ask_time',
            field=models.DateField(),
        ),
    ]
