# Generated by Django 2.0.4 on 2018-04-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0003_auto_20180410_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askinfo',
            name='ask_details',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='askinfo',
            name='ask_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('f', '男'), ('m', '女')], default='男', max_length=2),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_label',
            field=models.ManyToManyField(blank=True, to='Iknow.LabelInfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
