# Generated by Django 2.0.4 on 2018-04-11 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0004_auto_20180410_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 4, 11, 16, 41, 27, 117898)),
            preserve_default=False,
        ),
    ]
