# Generated by Django 2.0.4 on 2018-04-16 00:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0006_auto_20180411_1808'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='askinfo',
            managers=[
                ('maneger', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='askinfo',
            name='ask_details',
            field=models.CharField(blank=True, default=models.CharField(max_length=128, unique=True), max_length=600),
        ),
        migrations.AlterField(
            model_name='askinfo',
            name='ask_lable',
            field=models.ManyToManyField(default='生活', to='Iknow.LabelInfo'),
        ),
        migrations.AlterField(
            model_name='askinfo',
            name='ask_title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
