# Generated by Django 2.0.4 on 2018-04-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0007_auto_20180416_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_label',
            field=models.ManyToManyField(blank=True, default='生活', to='Iknow.LabelInfo'),
        ),
    ]
