# Generated by Django 2.0.4 on 2018-04-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0009_auto_20180419_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelinfo',
            name='lb_ask',
        ),
        migrations.RemoveField(
            model_name='labelinfo',
            name='lb_user',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_label',
            field=models.ManyToManyField(blank=True, to='Iknow.LabelInfo'),
        ),
    ]
