# Generated by Django 2.0.4 on 2018-04-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0010_auto_20180419_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askinfo',
            name='ask_lable',
            field=models.ManyToManyField(blank=True, to='Iknow.LabelInfo'),
        ),
    ]
