# Generated by Django 2.0.4 on 2018-04-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0012_auto_20180419_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askinfo',
            name='ask_lable',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_label',
        ),
    ]
