# Generated by Django 2.0.4 on 2018-04-19 11:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0014_auto_20180419_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_details', models.TextField()),
                ('re_time', models.DateTimeField(auto_now_add=True)),
                ('re_ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iknow.AskInfo')),
                ('re_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Iknow.UserInfo')),
            ],
        ),
        migrations.AlterModelManagers(
            name='labelinfo',
            managers=[
                ('maneger', django.db.models.manager.Manager()),
            ],
        ),
    ]
