# Generated by Django 2.0.4 on 2018-04-19 12:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0015_auto_20180419_1913'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='replyinfo',
            managers=[
                ('maneger', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='askinfo',
            name='ask_details',
            field=models.CharField(blank=True, default='如题', max_length=600),
        ),
    ]
