# Generated by Django 2.0.4 on 2018-04-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0016_auto_20180419_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='askinfo',
            old_name='ask_lable',
            new_name='ask_label',
        ),
    ]
