# Generated by Django 2.0.4 on 2018-04-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0017_auto_20180419_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyinfo',
            name='re_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iknow.UserInfo'),
        ),
    ]
