# Generated by Django 2.0.4 on 2018-05-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0018_auto_20180419_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askinfo',
            name='ask_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
