# Generated by Django 2.0.4 on 2018-05-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0019_auto_20180505_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askinfo',
            name='ask_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
