# Generated by Django 2.0.4 on 2018-05-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0024_auto_20180515_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='replyinfo',
            name='re_like',
            field=models.ManyToManyField(blank=True, related_name='re_like_user', to='Iknow.UserInfo'),
        ),
    ]
