# Generated by Django 2.0.4 on 2018-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iknow', '0025_replyinfo_re_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='replyinfo',
            name='re_bad',
            field=models.ManyToManyField(blank=True, related_name='re_bad_user', to='Iknow.UserInfo'),
        ),
    ]
